# Generated by Django 5.1.7 on 2025-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authapp', '0004_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
