# Generated by Django 5.1.7 on 2025-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
